### ISSUE TITLE
unable to deploy an instance on a VM host

### ISSUE THREAD

**Issue by vicenteg** [vicenteg/ansible-openstack#3]
```
root@ubuntu:~# nova boot --image "Cirros 0.3.1" --flavor m1.tiny test
+-------------------------------------+--------------------------------------+
| Property                            | Value                                |
+-------------------------------------+--------------------------------------+
| OS-EXT-STS:task_state               | scheduling                           |
| image                               | Cirros 0.3.1                         |
| OS-EXT-STS:vm_state                 | building                             |
| OS-EXT-SRV-ATTR:instance_name       | instance-00000002                    |
| flavor                              | m1.tiny                              |
| id                                  | 4dc8bcae-6f5d-4cc2-b941-b78a80646604 |
| security_groups                     | [{u'name': u'default'}]              |
| user_id                             | a7660af72b2c4ce8919c324b11b57564     |
| OS-DCF:diskConfig                   | MANUAL                               |
| accessIPv4                          |                                      |
| accessIPv6                          |                                      |
| progress                            | 0                                    |
| OS-EXT-STS:power_state              | 0                                    |
| OS-EXT-AZ:availability_zone         | nova                                 |
| config_drive                        |                                      |
| status                              | BUILD                                |
| updated                             | 2013-09-18T15:07:33Z                 |
| hostId                              |                                      |
| OS-EXT-SRV-ATTR:host                | None                                 |
| key_name                            | None                                 |
| OS-EXT-SRV-ATTR:hypervisor_hostname | None                                 |
| name                                | test                                 |
| adminPass                           | tw656ybx8RsY                         |
| tenant_id                           | dcac30094ab8425392bb1b0857a189c1     |
| created                             | 2013-09-18T15:07:33Z                 |
| metadata                            | {}                                   |
+-------------------------------------+--------------------------------------+
```

```
==> nova-conductor.log <==
2013-09-18 08:08:33.355 ERROR nova.openstack.common.rpc.amqp [req-d02428f5-466c-4a0a-9c41-a2f424f453a3 None None] Exception during message handling
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp Traceback (most recent call last):
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 430, in _process_data
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     rval = self.proxy.dispatch(ctxt, version, method, **args)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/dispatcher.py", line 133, in dispatch
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     return getattr(proxyobj, method)(ctxt, **kwargs)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 355, in compute_node_update
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     prune_stats)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 200, in compute_node_update
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     return IMPL.compute_node_update(context, compute_id, values, prune_stats)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 96, in wrapper
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     return f(*args, **kwargs)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 545, in compute_node_update
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     compute_ref = _compute_node_get(context, compute_id, session=session)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 455, in _compute_node_get
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp     raise exception.ComputeHostNotFound(host=compute_id)
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp ComputeHostNotFound: Compute host 1 could not be found.
2013-09-18 08:08:33.355 14914 TRACE nova.openstack.common.rpc.amqp
2013-09-18 08:08:33.359 ERROR nova.openstack.common.rpc.common [req-d02428f5-466c-4a0a-9c41-a2f424f453a3 None None] Returning exception Compute host 1 could not be found. to caller
2013-09-18 08:08:33.360 ERROR nova.openstack.common.rpc.common [req-d02428f5-466c-4a0a-9c41-a2f424f453a3 None None] ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 430, in _process_data\n    rval = self.proxy.dispatch(ctxt, version, method, **args)\n', '  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/dispatcher.py", line 133, in dispatch\n    return getattr(proxyobj, method)(ctxt, **kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 355, in compute_node_update\n    prune_stats)\n', '  File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 200, in compute_node_update\n    return IMPL.compute_node_update(context, compute_id, values, prune_stats)\n', '  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 96, in wrapper\n    return f(*args, **kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 545, in compute_node_update\n    compute_ref = _compute_node_get(context, compute_id, session=session)\n', '  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 455, in _compute_node_get\n    raise exception.ComputeHostNotFound(host=compute_id)\n', 'ComputeHostNotFound: Compute host 1 could not be found.\n']

==> nova-compute.log <==
2013-09-18 08:08:33.367 12858 ERROR nova.manager [-] Error during ComputeManager.update_available_resource: Compute host 1 could not be found.
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 430, in _process_data
    rval = self.proxy.dispatch(ctxt, version, method, **args)

  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/dispatcher.py", line 133, in dispatch
    return getattr(proxyobj, method)(ctxt, **kwargs)

  File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 355, in compute_node_update
    prune_stats)

  File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 200, in compute_node_update
    return IMPL.compute_node_update(context, compute_id, values, prune_stats)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 96, in wrapper
    return f(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 545, in compute_node_update
    compute_ref = _compute_node_get(context, compute_id, session=session)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 455, in _compute_node_get
    raise exception.ComputeHostNotFound(host=compute_id)

ComputeHostNotFound: Compute host 1 could not be found.
2013-09-18 08:08:33.367 12858 TRACE nova.manager Traceback (most recent call last):
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/manager.py", line 241, in periodic_tasks
2013-09-18 08:08:33.367 12858 TRACE nova.manager     task(self, context)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 3890, in update_available_resource
2013-09-18 08:08:33.367 12858 TRACE nova.manager     rt.update_available_resource(context)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/lockutils.py", line 242, in inner
2013-09-18 08:08:33.367 12858 TRACE nova.manager     retval = f(*args, **kwargs)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/compute/resource_tracker.py", line 272, in update_available_resource
2013-09-18 08:08:33.367 12858 TRACE nova.manager     self._sync_compute_node(context, resources)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/compute/resource_tracker.py", line 299, in _sync_compute_node
2013-09-18 08:08:33.367 12858 TRACE nova.manager     self._update(context, resources, prune_stats=True)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/compute/resource_tracker.py", line 354, in _update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     context, self.compute_node, values, prune_stats)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/conductor/api.py", line 621, in compute_node_update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     values, prune_stats)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/conductor/rpcapi.py", line 355, in compute_node_update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return self.call(context, msg, version='1.33')
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/proxy.py", line 80, in call
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return rpc.call(context, self._get_topic(topic), msg, timeout)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/__init__.py", line 140, in call
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return _get_impl().call(CONF, context, topic, msg, timeout)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/impl_kombu.py", line 798, in call
2013-09-18 08:08:33.367 12858 TRACE nova.manager     rpc_amqp.get_connection_pool(conf, Connection))
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 612, in call
2013-09-18 08:08:33.367 12858 TRACE nova.manager     rv = list(rv)
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 561, in __iter__
2013-09-18 08:08:33.367 12858 TRACE nova.manager     raise result
2013-09-18 08:08:33.367 12858 TRACE nova.manager ComputeHostNotFound_Remote: Compute host 1 could not be found.
2013-09-18 08:08:33.367 12858 TRACE nova.manager Traceback (most recent call last):
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 430, in _process_data
2013-09-18 08:08:33.367 12858 TRACE nova.manager     rval = self.proxy.dispatch(ctxt, version, method, **args)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/dispatcher.py", line 133, in dispatch
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return getattr(proxyobj, method)(ctxt, **kwargs)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 355, in compute_node_update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     prune_stats)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 200, in compute_node_update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return IMPL.compute_node_update(context, compute_id, values, prune_stats)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 96, in wrapper
2013-09-18 08:08:33.367 12858 TRACE nova.manager     return f(*args, **kwargs)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 545, in compute_node_update
2013-09-18 08:08:33.367 12858 TRACE nova.manager     compute_ref = _compute_node_get(context, compute_id, session=session)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 455, in _compute_node_get
2013-09-18 08:08:33.367 12858 TRACE nova.manager     raise exception.ComputeHostNotFound(host=compute_id)
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager ComputeHostNotFound: Compute host 1 could not be found.
2013-09-18 08:08:33.367 12858 TRACE nova.manager
2013-09-18 08:08:33.367 12858 TRACE nova.manager
```

**Comment by vicenteg** [comment]
Probably just related to low memory on VM. VM only had 512MB.
