### ISSUE TITLE
too many open files when running entire site.yml playbook

### ISSUE THREAD

**Issue by vicenteg** [vicenteg/ansible-openstack#6]
Sometimes occurs in the network-nodes playbook, sometimes in glance. Perhaps need to increase open file ulimits?

```
TASK: [configure glance to use the Identity service] **************************
fatal: [ubuntu-vm] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 382, in _executor
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 471, in _executor_internal
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 644, in _executor_internal_inner
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 768, in _make_tmp_path
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 703, in _low_level_exec_command
  File "/Library/Python/2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 185, in exec_command
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 672, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1035, in _get_handles
OSError: [Errno 24] Too many open files


FATAL: all hosts have already failed -- aborting
```

**Comment by vicenteg** [comment]
Not seen on real hardware -might be the result of automatic tuning of the value to a low number based on the low memory on VMs I was testing on.
